#!/bin/bash

# Script to compile and run gate-level simulation using Icarus Verilog
# Execute this script from the ~/lab8 directory

# --- Configuration ---
TB_MODULE_GATE="tb_gate_accelerator" # Testbench for gate-level simulation
VVP_OUTPUT_FILE="gate_sim.vvp"       # Compiled output for vvp
SIMULATION_LOG_FILE="gate_sim.log"   # Log file for simulation output
VCD_FILE_GATE="gate_sim_waves.vcd"   # VCD file generated by tb_gate_accelerator.v

# Netlist and Standard Cell Verilog Models (paths relative to script execution dir)
NETLIST_FILE="./output_synth_wsl/accelerator-100MHz/accelerator.netlist.fixed.v" # Assuming synth was run with O=./output_synth_wsl
# If you ran synth with O=../output_synth_wsl (from yosys-sta dir), then netlist is:
# NETLIST_FILE="./output_synth_wsl/accelerator-100MHz/accelerator.netlist.fixed.v"

# Assuming stdcells.v from freepdk-45nm is now directly in ~/lab8
NANGATE45_STDCELLS_V="./stdcells.v" 
# Optional: If stdcells.v is not comprehensive and basic cells are in yosys-sta's sim/cells.v
# NANGATE45_SIM_CELLS_BASIC="./yosys-sta/pdk/nangate45/sim/cells.v"

# --- Helper Functions ---
echocmd() {
  echo
  echo "----------------------------------------------------------------------"
  echo "--- $1"
  echo "----------------------------------------------------------------------"
}

# --- Script Execution ---
# Ensure we are in the lab8 directory
if [ ! -f "${TB_MODULE_GATE}.v" ]; then
    echo "Error: Testbench file ${TB_MODULE_GATE}.v not found. Run this script from ~/lab8."
    exit 1
fi
if [ ! -f "${NETLIST_FILE}" ]; then
    echo "Error: Netlist file ${NETLIST_FILE} not found. Run synthesis first."
    exit 1
fi
if [ ! -f "${NANGATE45_STDCELLS_V}" ]; then
    echo "Error: Standard cell Verilog model ${NANGATE45_STDCELLS_V} not found."
    exit 1
fi

# 1. Compile for gate-level simulation with Icarus Verilog
echocmd "Compiling with Icarus Verilog for Gate-Level Simulation"
# We will use stdcells.v as the primary library.
# Add NANGATE45_SIM_CELLS_BASIC if you find stdcells.v is missing basic gates (unlikely)
iverilog -o ${VVP_OUTPUT_FILE} \
    ${TB_MODULE_GATE}.v \
    ${NETLIST_FILE} \
    ${NANGATE45_STDCELLS_V} \
    -Wall # Enable all warnings for iverilog

if [ $? -ne 0 ]; then
    echo "Error: Icarus Verilog compilation failed."
    exit 1
fi
echo "Icarus Verilog compilation successful: ${VVP_OUTPUT_FILE} created."

# 2. Run the simulation using vvp
echocmd "Running Gate-Level Simulation (vvp)"
vvp ${VVP_OUTPUT_FILE} > ${SIMULATION_LOG_FILE}
# To see output directly on terminal and also save to log:
# vvp ${VVP_OUTPUT_FILE} | tee ${SIMULATION_LOG_FILE}

if [ $? -ne 0 ]; then
    echo "Error: VVP simulation run failed."
    #cat ${SIMULATION_LOG_FILE} # Print log if failed
    exit 1
fi
echo "Gate-Level Simulation finished. Log: ${SIMULATION_LOG_FILE}"
echo "VCD file (if enabled in TB): ${VCD_FILE_GATE}"

# 3. Extract Execution Time (Example)
echocmd "Extracting Execution Time from ${SIMULATION_LOG_FILE}"
EXECUTION_TIME_LINE=$(grep "Execution time:" ${SIMULATION_LOG_FILE})
if [ -n "${EXECUTION_TIME_LINE}" ]; then
    echo "${EXECUTION_TIME_LINE}"
    # Further parsing can be done here if needed
else
    echo "Could not automatically extract execution time from log."
    echo "Please check ${SIMULATION_LOG_FILE} manually for start and end times from your Testbench $display messages."
fi

echocmd "Gate-level simulation script finished."